---

- name: build inventory to check workshops
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: add student servers
    add_host:
      name: student{{ item }}
      ansible_host: student{{ item }}.{{ lab_domain }}
      ansible_user: student{{ item }}
      ansible_ssh_pass: "{{ lab_password }}"
      groups:
        - lab_environments
    loop: "{{ range(1, students + 1)| list }}"

- name: check progress on workshops and build report
  hosts: lab_environments
  vars:
    labs:
      - {"exercise": "exercise_1.3", "file_to_check": "apache.yml"}
      - {"exercise": "exercise_1.4", "file_to_check": "deploy_index_html.yml"}
      - {"exercise": "exercise_1.5", "file_to_check": "ftpserver.yml"}
      - {"exercise": "exercise_1.6", "file_to_check": "motd-facts.yml"}
      - {"exercise": "exercise_1.7", "file_to_check": "test_apache_role.yml"}
  tasks:
  - name: check labs
    include_tasks:
      file: tasks/gather_data.yml
    loop: "{{ labs }}"
      
  - name: copy over css files
    copy: 
      src: files/css
      dest: /usr/share/nginx/html/css
      remote_src: true
    delegate_to: localhost
    become: true
    run_once: true

  - name: template out report
    template:
      src: workshop_progress_report.html.j2
      dest: /usr/share/nginx/html/workshop_progress_report.html
      remote_src: true
    delegate_to: localhost
    become: true
    run_once: true

  - name: print report url
    debug:
      msg: http://{{ trainer}}.{{ lab_domain}}/workshop_progress_report.html
    run_once: true
    delegate_to: localhost
